_target_: src.models.cls_module.ClassificationModule
lr: !!float 6e-6
weight_decay: !!float 1e-5
optimizer: "adamw"

net:
  _target_: src.models.components.classification.audio_bilstm_net.AudioBiLSTMNet
  num_classes: 2
  dropout: !!float 0.5
  num_layers: 2
  hidden_size: 256
  embed_size: 256
  bidirectional: True
