_target_: src.models.reg_module.RegressionModule
lr: !!float 1e-5
weight_decay: !!float 1e-5
optimizer: "adam"

net:
  _target_: src.models.components.regression.audio_bilstm_net.AudioBiLSTMNet
  num_classes: 1
  dropout: !!float 0.5
  num_layers: 2
  hidden_size: 256
  embed_size: 256
  bidirectional: True
